version: "3.3"

services:
  proxy:
    image: "traefik:v2.2"
    command:
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"  
      - "$PWD/acme.json:/acme.json"
      - "$PWD/traefik.toml:/etc/traefik/traefik.toml"
    container_name: "traefik"
  web_1:
    image: nginx:latest
    container_name: "traefik_web_1"
    depends_on: 
      - php
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/
      - ./public:/var/www/html
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`traefik.ваш_сайт.ru`)"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.web_1.rule=Host(`домен.ru`)"
      - "traefik.http.services.web_1.loadbalancer.server.port=80"
      - "traefik.http.services.web_1.loadbalancer.passhostheader=false"
  web_2:
    image: nginx:latest
    container_name: "traefik_web_2"
    depends_on: 
      - php
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/
      - ./public:/var/www/html
    ports:
      - "5555:5555"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`traefik.akiryanov.ru`)"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.web_2.rule=Host(`сайт или IP`)"
      - "traefik.http.services.web_2.loadbalancer.server.port=80"
      - "traefik.http.services.web_2.loadbalancer.passhostheader=false"
  php:
    container_name: php
    image: php:7.4-fpm
    restart: always
    volumes:
     - ./public:/var/www/html
